<a href="https://colab.research.google.com/github/yusfilpulungan/python/blob/master/001_python_basic_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basic Introduction

## Data Structures
There are quite a few data structures available. The builtins data structures are: lists, tuples, dictionaries, strings, sets and frozensets.


### Strings
Strings are immutable sequence of letters, numbers or symbols named characters. The sequence of character is begin with 0 from the left to the right and -1 from the right to the left.
To create string, we need to use the ' '.

In [1]:
# Create String
string_a = 'Hello World'
string_a

'Hello World'

In [2]:
# Check Type
type(string_a)

str

In [3]:
# Show String Length
len(string_a)

11

In [4]:
# Select the nth Character from the Left
string_a[1]

'e'

### Lists
Lists can contain any type of objects. We use [1, 2, 3] to add numeric object but for character we need to use ['one', 'two', 'three']. A single list may contain DataTypes like Integers, Strings, as well as Objects.

Lists are mutable, and hence, they can be altered even after their creation.

Each data has an address referred to as an index. The index is begins with 0 from the left to the right and begins with -1 from the right to the left.

Create list

In [5]:
# Create an Empty List
list_fruits = []
list_fruits

[]

In [6]:
# Check Type
type(list_fruits)

list

In [7]:
# Create List
list_fruits = ['orange', 'apple', 'pear']
list_fruits

['orange', 'apple', 'pear']

Add items to the list

In [8]:
# Append an Item to the end of List
list_fruits.append('banana')
list_fruits

['orange', 'apple', 'pear', 'banana']

In [9]:
# Extend Items to List
list_fruits.extend(['kiwi', 'apple', 'banana', 'durian', 'rambutan', 'grape'])
list_fruits

['orange',
 'apple',
 'pear',
 'banana',
 'kiwi',
 'apple',
 'banana',
 'durian',
 'rambutan',
 'grape']

In [10]:
# Insert an Item to a Specific Index of a List
list_fruits.insert(2,'orange')
list_fruits

['orange',
 'apple',
 'orange',
 'pear',
 'banana',
 'kiwi',
 'apple',
 'banana',
 'durian',
 'rambutan',
 'grape']

Explore the list

In [11]:
# Count an Item
list_fruits.count('banana')

2

In [12]:
# View the nth Item
list_fruits[2]

'orange'

In [13]:
# View the nth Item
list_fruits[1:3]

['apple', 'orange']

In [14]:
# Sorts Items
list_fruits.sort(reverse=False)
list_fruits

['apple',
 'apple',
 'banana',
 'banana',
 'durian',
 'grape',
 'kiwi',
 'orange',
 'orange',
 'pear',
 'rambutan']

In [15]:
# Reverse Items
list_fruits.reverse()
list_fruits

['rambutan',
 'pear',
 'orange',
 'orange',
 'kiwi',
 'grape',
 'durian',
 'banana',
 'banana',
 'apple',
 'apple']

Remove items from the list

In [16]:
# Change the nth Item
list_fruits[2] = 'coconut'
list_fruits

['rambutan',
 'pear',
 'coconut',
 'orange',
 'kiwi',
 'grape',
 'durian',
 'banana',
 'banana',
 'apple',
 'apple']

In [17]:
# Remove the Nearest Item from List
list_fruits.remove('coconut')
list_fruits

['rambutan',
 'pear',
 'orange',
 'kiwi',
 'grape',
 'durian',
 'banana',
 'banana',
 'apple',
 'apple']

In [18]:
# Remove the nth Item
del list_fruits[1]
list_fruits

['rambutan',
 'orange',
 'kiwi',
 'grape',
 'durian',
 'banana',
 'banana',
 'apple',
 'apple']

In [19]:
# Remove the Multiple Items by Index Range
del list_fruits[4:6]
list_fruits

['rambutan', 'orange', 'kiwi', 'grape', 'banana', 'apple', 'apple']

In [20]:
# Remove Items by specifying step as [start:stop:step]
del list_fruits[0:6:2]
list_fruits

['orange', 'grape', 'apple', 'apple']

Show items that meet the condition

In [21]:
# Show List without Items
print([s for s in list_fruits if s != 'apple'])

['orange', 'grape']


In [22]:
# Show Multiple Items that Starts with X
print([s for s in list_fruits if s.startswith('o')])

['orange']


In [23]:
# Remove Multiple Items that Ends with X
print([s for s in list_fruits if s.endswith('e')])

['orange', 'grape', 'apple', 'apple']


In [24]:
# Remove Multiple Items that Start with X and Ends with Y
print([s for s in list_fruits if s.startswith('o') and s.endswith('e')])

['orange']


Remove list

In [25]:
# Remove List
list_fruits.clear()
list_fruits

[]

### Tuples
In someways a tuple is similar to a list in terms of indexing, nested objects and repetition but a tuple is immutable. We use (1, 2, 3) to add numeric object but for character we need to use ('one', 'two', 'three'). 

In [26]:
# Create Tuple
tuple_animals = ()
tuple_animals

()

In [27]:
# Check Type
type(tuple_animals)

tuple

In [28]:
# Create Tuple
tuple_animals = ('cat', 'lion', 'bear', 'dog', 'bird')
tuple_animals

('cat', 'lion', 'bear', 'dog', 'bird')

In [29]:
# Create Tuple
tuple_animals1 = 'cat', 'lion', 'bear', 'dog', 'bird'
tuple_animals1

('cat', 'lion', 'bear', 'dog', 'bird')

Explore the tuple

In [30]:
# Count an Item
tuple_animals.count('cat')

1

In [31]:
# Show the nth Item
tuple_animals[1]

'lion'

In [32]:
# Show range of Items
tuple_animals[1:3]

('lion', 'bear')

In [33]:
# Show range of Items
tuple_animals[:2]

('cat', 'lion')

In [34]:
# Sorts Items
sorted(tuple_animals, reverse=False)

['bear', 'bird', 'cat', 'dog', 'lion']

In [35]:
# Sorts Items
sorted(tuple_animals, reverse=True)

['lion', 'dog', 'cat', 'bird', 'bear']

Convert tuple to the list

In [36]:
list_animals = list(tuple_animals)
list_animals

['cat', 'lion', 'bear', 'dog', 'bird']

### Sets
Python also includes a data type for sets. A set is an unordered collection with no duplicate elements. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.
Curly braces or the set() function can be used to create sets. Note: to create an empty set you have to use set(), not {}.
No index in sets since the values are unordered.

Create set

In [37]:
# Create an Empty Set
set_groceries_a = set()
set_groceries_a

set()

In [38]:
# Check Type
type(set_groceries_a)

set

In [39]:
# Create Set
set_groceries_a = {'milk', 'diaper', 'parfume', 'noodle', 'bread', 'vegetable', 'milk', 'vegetable'}
set_groceries_a

{'bread', 'diaper', 'milk', 'noodle', 'parfume', 'vegetable'}

In [40]:
# Create Set
set_groceries_b = {'milk', 'ball', 'towel', 'noodle', 'tea', 'vegetable'}
set_groceries_b

{'ball', 'milk', 'noodle', 'tea', 'towel', 'vegetable'}

Add items to the set

In [41]:
# Add an Item
set_groceries_a.add('sausage') 
set_groceries_a

{'bread', 'diaper', 'milk', 'noodle', 'parfume', 'sausage', 'vegetable'}

In [42]:
# Add Items
set_groceries_a.update(['beef','cheese','tofu']) 
set_groceries_a

{'beef',
 'bread',
 'cheese',
 'diaper',
 'milk',
 'noodle',
 'parfume',
 'sausage',
 'tofu',
 'vegetable'}

Explore the set

In [43]:
# Search for Item Availability
'milk' in set_groceries_a

True

In [44]:
# Show Union (items in a or b or both)
set_groceries_a | set_groceries_b

{'ball',
 'beef',
 'bread',
 'cheese',
 'diaper',
 'milk',
 'noodle',
 'parfume',
 'sausage',
 'tea',
 'tofu',
 'towel',
 'vegetable'}

In [0]:
# Show Intersection (items in both a and b)
set_groceries_a & set_groceries_b

In [0]:
# Show Symetric Difference (items in a or b but not both)
set_groceries_a ^ set_groceries_b

In [0]:
# Show Difference (items in a but not in b)
set_groceries_a - set_groceries_b

Remove items from the set

In [0]:
# Remove an Item
set_groceries_a.remove('sausage') 
set_groceries_a

The frozenset() is an inbuilt function is Python which takes an iterable object as input and makes them immutable. Simply it freezes the iterable objects and makes them unchangeable.

In [0]:
# Create Frozenset
frzset_groceries_a = frozenset(set_groceries_a)
frzset_groceries_a

Remove set

In [0]:
# Remove Set
set_groceries_b.clear()
set_groceries_b

### Dictionary
Dictionaries are sometimes found in other languages as “associative memories”.
Unlike list and tuples, which are indexed by a range of numbers, dictionaries are indexed by keys. Keys can be any immutable type.
The immutable frozenset and tuple can be used as keys. A mutable object cannot be used as a key. 
Another requirement is that the keys are unique (within one dictionary).
A pair of braces creates an empty dictionary {}

Create dictionary

In [0]:
# Create an Empty Dictionary
dict_colors = {}

In [46]:
# Create Dictionary
dict_colors = {'apple':'red',
               'blueberry':'blue',
               'avocado':'green',
               'banana':'yellow'}
dict_colors

{'apple': 'red', 'avocado': 'green', 'banana': 'yellow', 'blueberry': 'blue'}

In [47]:
# Show Access Key
dict_colors.keys()

dict_keys(['apple', 'blueberry', 'avocado', 'banana'])

Use the dictionary

In [48]:
# Show the Value from a Key
print(dict_colors.get('avocado'))

green


In [49]:
# Show the Value from a Key
print('The color of an avocado is %s' % dict_colors['avocado'])

The color of an avocado is green


In [50]:
# Show the Values from All Keys
for key, val in dict_colors.items():
    print("%s : %s" % (key, val))

apple : red
blueberry : blue
avocado : green
banana : yellow


##NumPy
NumPy is a basic package for scientific computing with Python and especially for data analysis. NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. 

Install and import library

In [0]:
# Install library
!pip install numpy

In [0]:
# Import library
import numpy as np

### Array
An array is a special variable, which can hold more than one value at a time. Arrays are used to store multiple values in one single variable


Create array

In [52]:
# Create an Array
array = np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# Create an Array with Shape
array_a = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
array_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
# Create an Array based on Other Array
array_b = array_a + 6
array_b

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [55]:
# Concat Array a and Array b (Horizontally)
np.concatenate([array_a,array_b],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12],
       [ 7,  8,  9, 13, 14, 15]])

In [56]:
# Concat Array a and Array b (Vertically)
np.concatenate([array_a,array_b],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

Explore the array

In [57]:
# Show the nth Row Index and nth Coulmn Index of an Array
array_a[0,1]

2

In [58]:
# Show the nth Row Index of an Array
array_a[0,:]

array([1, 2, 3])

In [59]:
# Show the nth Column Index of an Array
array_a[:,1]

array([2, 5, 8])

Assign value

In [60]:
# Assign Value to the nth Row Index of an Array
array_a[0,:] = 5
array_a

array([[5, 5, 5],
       [4, 5, 6],
       [7, 8, 9]])

Basic operation

In [61]:
# Summation
array_a + array_b

array([[12, 13, 14],
       [14, 16, 18],
       [20, 22, 24]])

In [62]:
# Multiplication
array_a * 2

array([[10, 10, 10],
       [ 8, 10, 12],
       [14, 16, 18]])

In [63]:
# Multiplication
array_a * array_b

array([[ 35,  40,  45],
       [ 40,  55,  72],
       [ 91, 112, 135]])

In [64]:
# Sum All Values in an Array
array_a.sum()

54

In [65]:
# Log
np.log(array_a)

array([[1.60943791, 1.60943791, 1.60943791],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

### Matrix

Create matrix

In [66]:
# Create Matrix
matrix_a = np.matrix([1,2,3,4,5,6,7,8,9]).reshape((3,3))
matrix_a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
# Create a Matrix based on Other Matrix
matrix_b = matrix_a + 6
matrix_b

matrix([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

Basic operation

In [68]:
# Summation
matrix_a + matrix_b

matrix([[ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]])

In [69]:
# Multiplication
matrix_a * matrix_b

matrix([[ 66,  72,  78],
        [156, 171, 186],
        [246, 270, 294]])

## Pandas
Pandas is a software library written for the Python programming language for data manipulation and analysis. We can analyze data in pandas with Series and DataFrames.

Import library

In [0]:
# Import Library
import pandas as pd

### Series

Series is one dimensional(1-D) array defined in pandas that can be used to store any data type.

Create series

In [71]:
# Create a Series
series_a = pd.Series([12,-4,7,9])
series_a

0    12
1    -4
2     7
3     9
dtype: int64

In [72]:
# Create a Series with Index
series_a = pd.Series([12,-4,7,9,8,8,7,9], index=['a','b','c','d','e','f','g','h'])
series_a

a    12
b    -4
c     7
d     9
e     8
f     8
g     7
h     9
dtype: int64

Explore the series

In [73]:
# Show the nth Value of a Series
series_a[2]

7

In [74]:
# Show the Value of a Series based on Index
series_a['a']

12

In [75]:
# Set the nth Values of a Series
series_a[1] = 0
series_a

a    12
b     0
c     7
d     9
e     8
f     8
g     7
h     9
dtype: int64

In [76]:
# Filtering Values
series_a[series_a > 8]

a    12
d     9
h     9
dtype: int64

In [77]:
# Operations and Mathematical Functions
series_a + 2

a    14
b     2
c     9
d    11
e    10
f    10
g     9
h    11
dtype: int64

In [78]:
# Show Unique Value
series_a.unique()

array([12,  0,  7,  9,  8])

In [79]:
# Count Each Value
series_a.value_counts()

7     2
8     2
9     2
12    1
0     1
dtype: int64

### DataFrame
The DataFrame is a tabular data structure very similar to the Spreadsheet (the most familiar are Excel
spreadsheets). This data structure is designed to extend the case of the Series to multiple dimensions.

Create Data Frame

In [80]:
# Create Data Frame
data = {'color' : ['blue','green','yellow','red','white'],
        'object' : ['ball','pen','pencil','paper','mug'],
        'price' : [1.2,1.0,0.6,0.9,1.7]}
df_stationary_a = pd.DataFrame(data)
df_stationary_a

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [81]:
# Select Columns and Create a New Data Frame
df_stationary_b = pd.DataFrame(df_stationary_a, columns=['object','price'])
df_stationary_b

object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.7

In [82]:
# Set Index for the Data Frame
df_stationary_c = pd.DataFrame(data, index=['one','two','three','four','five'])
df_stationary_c

color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6
four      red   paper    0.9
five    white     mug    1.7

Import Data

In [83]:
# Import Data
df_churn = pd.read_csv('https://raw.githubusercontent.com/rc-dbe/bigdatacertification/master/dataset/churn.csv', sep=';',)
df_churn

customerID  gender SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female            No  ...           2985       2985.0     No
1     5575-GNVDE    Male            No  ...           5695      18895.0     No
2     3668-QPYBK    Male            No  ...           5385      10815.0    Yes
3     7795-CFOCW    Male            No  ...            423     184075.0     No
4     9237-HQITU  Female            No  ...            707      15165.0    Yes
...          ...     ...           ...  ...            ...          ...    ...
7038  6840-RESVB    Male            No  ...            848      19905.0     No
7039  2234-XADUH  Female            No  ...           1032      73629.0     No
7040  4801-JZAZL  Female            No  ...            296      34645.0     No
7041  8361-LTMKD    Male           Yes  ...            744       3066.0    Yes
7042  3186-AJIEK    Male            No  ...          10565      68445.0     No

[7043 rows x 21 columns]

Data Exploration

In [84]:
# Show Missing Values on Data Frame
df_churn.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [0]:
# Impute Missing Values with Median Value
median = df_churn["TotalCharges"].median()
df_churn["TotalCharges"].fillna(median, inplace=True)

In [86]:
# Check the Data Information
df_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null object
Partner             7043 non-null object
Dependents          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null int64
TotalCharges        7043 non-null float64
Churn               7043 non-null object
dtypes: float64(1), int64(2), obj

In [87]:
# Describe the Statistics of Data
df_churn.describe()

tenure  MonthlyCharges   TotalCharges
count  7043.000000     7043.000000    7043.000000
mean     32.371149     3517.437456  126112.150930
std      24.559481     3634.996251  192405.057371
min       0.000000       19.000000      19.000000
25%       9.000000      647.500000    7580.500000
50%      29.000000     1885.000000   36769.000000
75%      55.000000     7015.000000  142715.000000
max      72.000000    11875.000000  867245.000000

In [0]:
# Save Data Frame as CSV
df_churn.to_csv('churn bersih.csv', index=False)

# Data Design and Transformation with Pandas

It is often the case with data science projects that you’ll have to deal with messy or incomplete data. The raw data we obtain from different data sources is often unusable at the beginning. All the activity that you do on the raw data to make it “clean” enough to input to your analytical algorithm is called data wrangling.

In basic terms data wrangling is the process of unifying and organising different data sets. This step iteratively changes the shape of a dataset until it works well for finding insights or building a good analytic model. Data wrangling is the process where individuals manually convert and map raw data into another format in order to make it more accessible and usable. 

Pandas is mainly used for machine learning in form of dataframes. Pandas allow importing data of various file formats such as csv, excel etc. Pandas allows various data manipulation operations such as groupby, join, merge, melt, concatenation as well as data cleaning features such as filling, replacing or imputing null values. The Pandas library provides useful functions to support Data Wrangling tasks.

Import Libraries

In [0]:
# Import Libraries for Data Manupulation
import numpy as np
import pandas as pd

## Joining Data

Organizations typically find that their data comes from many different sources and this means that it can become scattered and unorganised. Joining data is pusposed to organise different data sets.

### Concatenating

Concatenating is defined as combining multiple data sources together. The concat function is performing concatenation operations along an axis. Let us create different objects and do concatenation.

Create data frame

In [90]:
# Create data frame 1
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3]) 
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [91]:
# Create data frame 2
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [92]:
# Create data frame 3
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[0, 1, 2, 3])
df3

A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [93]:
# Create data frame 4
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                    'D': ['D2', 'D3', 'D6', 'D7'],
                    'F': ['F2', 'F3', 'F6', 'F7']},
                    index=[2, 3, 6, 7])
df4

B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

Concat the same size data frame vertically

In [94]:
# Concat Data Frame
pd.concat([df1, df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [95]:
# Concat Data Frame with Keys
pd.concat([df1, df2, df3], keys=['df1', 'df2'])

A   B   C   D
df1 0  A0  B0  C0  D0
    1  A1  B1  C1  D1
    2  A2  B2  C2  D2
    3  A3  B3  C3  D3
df2 4  A4  B4  C4  D4
    5  A5  B5  C5  D5
    6  A6  B6  C6  D6
    7  A7  B7  C7  D7

Concat the same size data frame horizontally

In [96]:
# Concat Data Frame
pd.concat([df1, df3], axis=1)

A   B   C   D    A    B    C    D
0  A0  B0  C0  D0   A8   B8   C8   D8
1  A1  B1  C1  D1   A9   B9   C9   D9
2  A2  B2  C2  D2  A10  B10  C10  D10
3  A3  B3  C3  D3  A11  B11  C11  D11

In [97]:
# Concat Data Frame with Keys
pd.concat([df1, df3], axis=1, keys=['df1', 'df2'])

df1              df2               
    A   B   C   D    A    B    C    D
0  A0  B0  C0  D0   A8   B8   C8   D8
1  A1  B1  C1  D1   A9   B9   C9   D9
2  A2  B2  C2  D2  A10  B10  C10  D10
3  A3  B3  C3  D3  A11  B11  C11  D11

Concat the different size data frame vertically

In [98]:
# Concat with Join Outer
pd.concat([df1, df4], join='outer', keys=['df1', 'df4'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A   B    C   D    F
df1 0   A0  B0   C0  D0  NaN
    1   A1  B1   C1  D1  NaN
    2   A2  B2   C2  D2  NaN
    3   A3  B3   C3  D3  NaN
df4 2  NaN  B2  NaN  D2   F2
    3  NaN  B3  NaN  D3   F3
    6  NaN  B6  NaN  D6   F6
    7  NaN  B7  NaN  D7   F7

In [99]:
# Concat with Join Inner
pd.concat([df1, df4], join='inner', keys=['df1', 'df4'])

B   D
df1 0  B0  D0
    1  B1  D1
    2  B2  D2
    3  B3  D3
df4 2  B2  D2
    3  B3  D3
    6  B6  D6
    7  B7  D7

Concat the different size data frame horizontally

In [100]:
# Concat with Join Outer
pd.concat([df1, df4], axis=1, join='outer', keys=['df1', 'df4'])

df1                 df4          
     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [101]:
# Concat with Join Inner
pd.concat([df1, df4], axis=1, join='inner', keys=['df1', 'df4'])

df1             df4        
    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

Ignoring indexes on the concatenation axis

In [102]:
# Concat and Ignore Index
pd.concat([df1, df4], axis=1, join='outer', ignore_index=True)

0    1    2    3    4    5    6
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

### Merging

Merge operations combine data by linking rows using key(s). These operations are central to relational databases. The merge function in pandas is the main entry point for using these algorithms on your data.

Create data frame

In [103]:
# Create Pet Weight Data Frame
df_pets_age = pd.DataFrame( {'pet'  : ['cat', 'cat', 'dog', 'dog', 'dog', 'otter', 'otter'],
                             'age'  : [1, 1, 3, 3, 5, 2, 4]})
df_pets_age

pet  age
0    cat    1
1    cat    1
2    dog    3
3    dog    3
4    dog    5
5  otter    2
6  otter    4

In [104]:
# Create Pet Color Data Frame
df_pets_color = pd.DataFrame({'pet': ['cat', 'dog', 'otter', 'lion'],
                             'color' : ['white', 'grey', 'brown', 'red']})
df_pets_color

pet  color
0    cat  white
1    dog   grey
2  otter  brown
3   lion    red

In [105]:
# Create Animal Type Data Frame
df_animals_type = pd.DataFrame({'animal': ['cat', 'dog', 'otter', 'lion'],
                                'type' : ['tame', 'tame', 'tame', 'wild']})
df_animals_type

animal  type
0    cat  tame
1    dog  tame
2  otter  tame
3   lion  wild

Merge with the same key column name

In [106]:
# Merge Pet Age and Pet Color based on pet Column
df_pets = pd.merge(df_pets_age, df_pets_color, on='pet')
df_pets

pet  age  color
0    cat    1  white
1    cat    1  white
2    dog    3   grey
3    dog    3   grey
4    dog    5   grey
5  otter    2  brown
6  otter    4  brown

If the column names are different in each data frame, you can specify them separately:

In [107]:
# Merge Pet Weight and Pet Color based on pet Column and animal Column
df_pets1 = pd.merge(df_pets_age, df_animals_type, left_on='pet', right_on='animal')
df_pets1

pet  age animal  type
0    cat    1    cat  tame
1    cat    1    cat  tame
2    dog    3    dog  tame
3    dog    3    dog  tame
4    dog    5    dog  tame
5  otter    2  otter  tame
6  otter    4  otter  tame

### Reshaping

Reshaping means the transformation of the structure of data to make it suitable for further analysis.

Create data frame

In [108]:
# Create Data Frame
df_city = pd.DataFrame({'kecamatan' : pd.Series([21, 30], index =['medan', 'bandung']), 
                        'kelurahan' : pd.Series([151, 151], index =['medan', 'bandung']),
                        'area' : pd.Series([265, 167], index =['medan', 'bandung'])})
df_city.index.name = 'city'
df_city

kecamatan  kelurahan  area
city                               
medan           21        151   265
bandung         30        151   167

Using the stack method on this data pivots the columns into the rows, producing a Series:

In [110]:
# Stack Data
result = df_city.stack()
result

city              
medan    kecamatan     21
         kelurahan    151
         area         265
bandung  kecamatan     30
         kelurahan    151
         area         167
dtype: int64


From a hierarchically-indexed Series, you can rearrange the data back into a DataFrame with unstack:

In [111]:
# Unstack Data
result.unstack()

kecamatan  kelurahan  area
city                               
medan           21        151   265
bandung         30        151   167


By default the innermost level is unstacked (same with stack). You can unstack a different level by passing a level number or name:

In [112]:
# Unstack in Different Level
result.unstack(0)

city       medan  bandung
kecamatan     21       30
kelurahan    151      151
area         265      167

In [113]:
# Unstack in Different Level
result.unstack('city')

city       medan  bandung
kecamatan     21       30
kelurahan    151      151
area         265      167

## Data Cleansing

### Removing Duplicates

Duplicate rows may be found in a DataFrame for any number of reasons. Here is an example. We use pet dataframe that already created before.

Show data frame

In [114]:
# Show the Data Frame
df_pets

pet  age  color
0    cat    1  white
1    cat    1  white
2    dog    3   grey
3    dog    3   grey
4    dog    5   grey
5  otter    2  brown
6  otter    4  brown

The DataFrame method duplicated returns a boolean Series indicating whether each row is a duplicate or not:

In [115]:
# Check for Duplication
df_pets.duplicated()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
dtype: bool

Relatedly, drop_duplicates returns a DataFrame where the duplicated array is True:

In [116]:
# Drop Duplicates in The Dataframe
df_pets.drop_duplicates()

pet  age  color
0    cat    1  white
2    dog    3   grey
4    dog    5   grey
5  otter    2  brown
6  otter    4  brown

Drop duplicates based on one column

In [117]:
# Drop Duplicates based on Column Pet
df_pets.drop_duplicates(['pet'])

pet  age  color
0    cat    1  white
2    dog    3   grey
5  otter    2  brown

In [118]:
# Drop Duplicates based on Column Weight
df_pets.drop_duplicates(['age'])

pet  age  color
0    cat    1  white
2    dog    3   grey
4    dog    5   grey
5  otter    2  brown
6  otter    4  brown

In [119]:
# Drop Duplicates based on Column Gender
df_pets.drop_duplicates(['color'])

pet  age  color
0    cat    1  white
2    dog    3   grey
5  otter    2  brown

Drop duplicates based on more than one columns

In [120]:
# Drop Duplicates based on Column Pet and Weight
df_pets.drop_duplicates(['pet', 'age'])

pet  age  color
0    cat    1  white
2    dog    3   grey
4    dog    5   grey
5  otter    2  brown
6  otter    4  brown

### Replacing Values

In replacing values, we replace values with different new values. We use pet data frame that already created before.

Show data frame

In [121]:
# Show the Data Frame
df_pets

pet  age  color
0    cat    1  white
1    cat    1  white
2    dog    3   grey
3    dog    3   grey
4    dog    5   grey
5  otter    2  brown
6  otter    4  brown

If we consider that otter with the age of 4 is an uncorrect and unknown data, we can replace these values with NA values (missing values).

In [122]:
# Set Value as Missing Data
df_pets.replace(4, np.nan)

pet  age  color
0    cat  1.0  white
1    cat  1.0  white
2    dog  3.0   grey
3    dog  3.0   grey
4    dog  5.0   grey
5  otter  2.0  brown
6  otter  NaN  brown

Replace multiple values at once

In [123]:
# Set 4 and 5 Values as Missing Data
df_pets.replace([4, 5], np.nan)

pet  age  color
0    cat  1.0  white
1    cat  1.0  white
2    dog  3.0   grey
3    dog  3.0   grey
4    dog  NaN   grey
5  otter  2.0  brown
6  otter  NaN  brown

Replace multiple values with different value for each

In [124]:
# Set 4 as Missing Data and 5 as 10
df_pets.replace({4: np.nan, 5: 10})

pet   age  color
0    cat   1.0  white
1    cat   1.0  white
2    dog   3.0   grey
3    dog   3.0   grey
4    dog  10.0   grey
5  otter   2.0  brown
6  otter   NaN  brown

Create pet data with missing value

In [125]:
# Create Data Frame with Missing Value
df_pets_a = df_pets.replace({4: np.nan, 5: 10})
df_pets_a

pet   age  color
0    cat   1.0  white
1    cat   1.0  white
2    dog   3.0   grey
3    dog   3.0   grey
4    dog  10.0   grey
5  otter   2.0  brown
6  otter   NaN  brown

### Impute Missing Values

Filling in missing data with the fill NA method. Here is an example. We use pet data frame with missing value that already created before.

Show data frame

In [126]:
# Show Data Frame
df_pets_a

pet   age  color
0    cat   1.0  white
1    cat   1.0  white
2    dog   3.0   grey
3    dog   3.0   grey
4    dog  10.0   grey
5  otter   2.0  brown
6  otter   NaN  brown

Search for column with missing values

In [127]:
# Show Missing Values on Data Frame
df_pets_a.isnull().sum()

pet      0
age      1
color    0
dtype: int64

Impute missing value

In [128]:
# Impute Missing Values with Median Value
median = df_pets_a['age'].median()
df_pets_a['age'].fillna(median, inplace=True)
df_pets_a

pet   age  color
0    cat   1.0  white
1    cat   1.0  white
2    dog   3.0   grey
3    dog   3.0   grey
4    dog  10.0   grey
5  otter   2.0  brown
6  otter   2.5  brown

Recheck the missing values

In [129]:
# Show Missing Values on Data Frame
df_pets_a.isnull().sum()

pet      0
age      0
color    0
dtype: int64

### Filtering

Filtering value is largely a matter of applying array operations. Consider a data frame with some normally distributed data:

In [130]:
# Create Data Frame with Random Value with 1000 Rows and 4 Columns
np.random.seed(12345)
df_random = pd.DataFrame(np.random.randn(1000, 4))
df_random

0         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
..        ...       ...       ...       ...
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

In [131]:
# Describe the Data
df_random.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

Find values in one of the columns exceeding three in magnitude

In [132]:
# Find Values in Column 2 which is Exceeding 3 in Magnitude
column2 = df_random[2]
column2[np.abs(column2) > 3]

5      3.248944
102    3.176873
324    3.260383
499   -3.056990
586   -3.184377
Name: 2, dtype: float64

Select all rows having a value exceeding 3 or -3

In [133]:
# Select Rows Having a Value Exceeding 3 in Magnitude
df_random[(np.abs(df_random) > 3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846